name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          purs-tidy: "latest"
          spago: "unstable"

      - uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: spago install

      - name: Build source
        run: spago build --offline --censor-stats --strict --pedantic-packages

      - name: Run tests
        run: spago test

      - name: Check formatting
        run: purs-tidy check src test
